// VENDORED LIBRARIES: every entry in web/package.json `vendor` is a flat file in shared/,
// generated by scripts/sync-vendor.ts from the pinned dependency. Its header carries the pin
// and a hash of the body, so a stale sync or a hand edit fails here instead of shipping.
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { lstatSync, readFileSync } from 'node:fs'
import { test } from 'node:test'

const pkg = JSON.parse(readFileSync(new URL('../../web/package.json', import.meta.url), 'utf8'))
const packageOf = (spec: string) => spec.split('/').slice(0, spec.startsWith('@') ? 2 : 1).join('/')

test('Given the vendor list, when it is read, then it names at least the ranking library', () => {
	assert.equal(pkg.vendor?.['@rascaltwo/pairwise-sorter'], 'pairwise.js')
})

for (const [spec, file] of Object.entries<string>(pkg.vendor ?? {})) {
	test(`Given vendored ${spec}, when its header is checked, then it is the pinned version, unedited and linked from web/`, () => {
		const pin = pkg.dependencies?.[packageOf(spec)]
		assert.ok(pin, `${spec} is vendored but not in web/package.json dependencies`)
		const [line1, line2, ...rest] = readFileSync(new URL(`../../shared/${file}`, import.meta.url), 'utf8').split('\n')
		assert.ok(line1!.includes(`${spec} (${pin})`), `shared/${file} is not ${spec} ${pin} — run scripts/sync-vendor.ts`)
		const sha = createHash('sha256').update(rest.join('\n')).digest('hex')
		assert.equal(line2, `// body-sha256: ${sha}`, `shared/${file} was edited by hand — regenerate it`)
		// The web/ symlink is what makes it a shared file to parity, deploy and the dev server.
		assert.ok(lstatSync(new URL(`../../web/${file}`, import.meta.url)).isSymbolicLink(), `web/${file} is not a symlink into shared/ — run scripts/sync-vendor.ts`)
	})
}
