#!/usr/bin/env bash
#
# The test that was missing, and the reason three coordination bugs shipped in one
# day: it asserts the parity gate against the health body the SERVER ACTUALLY
# EMITS, generated by running the server's own code — not against a fixture
# hand-written from what the gate's author expected.
#
# A fixture built from the same assumption as the code under test confirms the
# assumption instead of testing it. That is how `{ ok: true, sharedSha256 }` (ES6
# shorthand publishing the variable's name) sat opposite a gate reading `shared`:
# both sides individually reasonable, both sides tested, nothing connecting them.
# Every stub in this repo encodes somebody's belief about the wire key. This one
# imports it.
#
# VERIFYING THIS TEST CAN FAIL: do it on a COPY, never in place.
# The obvious move is `sed -i '' s/shared/sharedSha256/` on the gate or on
# shared-hash.ts, run this, then restore. Don't. Those files are read by other
# people and other agents while you hold them mutated, and a transient wrong
# state reads as a real mismatch — which once cost this team a round of
# cross-wired "you changed it / no you changed it" over a key that was correct
# the whole time. Copy the repo to a scratch dir and drift it there.
#
# Usage: ./scripts/test-parity-contract.sh
# Requires: sync-server/node_modules (npm ci in sync-server/).
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

[ -d "$REPO/sync-server/node_modules" ] || {
  echo "SKIP: sync-server/node_modules absent — run 'npm ci' in sync-server/ first." >&2
  echo "      Refusing to pass silently: this check is the only thing tying the" >&2
  echo "      gate's expected wire key to the one the server emits." >&2
  exit 1; }

# Generate the body by RUNNING the server's own healthBody(). A module entry
# rather than `tsx -e`, because shared-hash.ts has top-level await.
TMP="$REPO/sync-server/src/.emit-health.ts"
printf "import { healthBody } from './shared-hash'\nconsole.log(JSON.stringify(healthBody()))\n" > "$TMP"
SRV=""
# An EXIT trap's LAST command sets the script's status, so a bare `kill; wait`
# made every run — pass or fail — exit 143 (128+SIGTERM) and the test uniformly
# red. Capture the real status first and exit with it.
# Every step is `|| :` because `set -e` aborts the function on the first non-zero
# status — and `wait` on a SIGTERMed job ALWAYS returns 143, so the bare version
# never reached `exit "$rc"` and every run exited 143, pass or fail.
cleanup() { rc=$?; if [ -n "$SRV" ]; then kill "$SRV" 2>/dev/null || :; wait "$SRV" 2>/dev/null || :; fi
           rm -f "$TMP"; exit "$rc"; }
trap cleanup EXIT
BODY="$(cd "$REPO/sync-server" && npx tsx src/.emit-health.ts | tail -1)"
rm -f "$TMP"
[ -n "$BODY" ] || { echo "FAIL: could not generate a health body from sync-server" >&2; exit 1; }
echo "server emits: $(printf '%s' "$BODY" | cut -c1-80)…"

printf '%s' "$BODY" > /tmp/parity-contract-health.json
python3 - 9788 /tmp/parity-contract-health.json <<'PY' &
import http.server, sys
class H(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        b = open(sys.argv[2]).read().encode()
        self.send_response(200); self.send_header('content-length', str(len(b)))
        self.end_headers(); self.wfile.write(b)
    def log_message(self, *a): pass
http.server.HTTPServer(('127.0.0.1', int(sys.argv[1])), H).serve_forever()
PY
SRV=$!
until curl -fsS --max-time 1 -o /dev/null http://127.0.0.1:9788/health 2>/dev/null; do :; done

"$REPO/scripts/assert-shared-parity.sh" --api-base http://127.0.0.1:9788 \
  || { echo; echo "FAIL: the gate rejected the body the server actually emits." >&2
       echo "      Compare the wire key in sync-server/src/shared-hash.ts against" >&2
       echo "      the key assert-shared-parity.sh reads." >&2; exit 1; }
echo "PASS: the gate accepts the server's real health body."
